parameters:
#    acme_dumy.example.class: Acme\DumyBundle\Example

services:
#    acme_dumy.example:
#        class: %acme_dumy.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
